-- PostgreSQL 호환 초기 데이터 삽입 스크립트
-- Neon SQL Editor에서 이 파일 전체를 복사해서 실행하세요

-- 사용자 데이터 (이미 있으면 스킵)
INSERT INTO "User" (id, email, password, name, role, status, "createdAt", "updatedAt") 
VALUES (1, 'sti60val@gmail.com', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '정성인', 'SUPER_ADMIN', 'ACTIVE', now(), now())
ON CONFLICT (email) DO NOTHING;

-- 현재 주 투표 세션 (11월 3일-7일)
INSERT INTO "VoteSession" (id, "weekStartDate", "startTime", "endTime", "isActive", "isCompleted", "createdAt", "updatedAt")
VALUES (1, '2025-11-03 00:00:00', '2025-11-02 00:00:00', '2025-11-06 23:59:59', true, false, now(), now())
ON CONFLICT (id) DO NOTHING;

-- 지난 주 투표 세션 (10월 27일-31일) - 완료됨
INSERT INTO "VoteSession" (id, "weekStartDate", "startTime", "endTime", "isActive", "isCompleted", "createdAt", "updatedAt")
VALUES (2, '2025-10-27 00:00:00', '2025-10-26 00:00:00', '2025-10-30 23:59:59', false, true, now(), now())
ON CONFLICT (id) DO NOTHING;

-- 지난 주 투표 데이터 (목, 금)
INSERT INTO "Vote" (id, "userId", "voteSessionId", "selectedDays", "createdAt", "updatedAt")
VALUES (1, 1, 2, '["THU","FRI"]', now(), now())
ON CONFLICT (id) DO NOTHING;

-- 현재 주 투표 데이터 (수, 금)
INSERT INTO "Vote" (id, "userId", "voteSessionId", "selectedDays", "createdAt", "updatedAt")
VALUES (2, 1, 1, '["WED","FRI"]', now(), now())
ON CONFLICT (id) DO NOTHING;

-- 지난 주 경기 데이터 (10월 30일)
INSERT INTO "Game" (id, date, time, location, "gameType", "eventType", "memberNames", "selectedMembers", "mercenaryCount", "autoGenerated", confirmed, "createdById", "createdAt", "updatedAt")
VALUES (1, '2025-10-30 12:00:00', '19:00', '풋살장', 'FRIENDLY', '풋살', '["정성인"]', '["정성인"]', 0, false, true, 1, now(), now())
ON CONFLICT (id) DO NOTHING;

